### ISSUE TITLE
ImportError: cannot import name 'Markup' from 'jinja2'

### ISSUE THREAD

**Issue by samcro1967** [JVT038/MetaTube#27]
Container fails to start.  Removed the database, container, and image to start from fresh and get the same results.  Any ideas?

```
Traceback (most recent call last):                                                                                                                                                                                 File "//config/metatube.py", line 5, in <module>
    from metatube import create_app, socketio
  File "/config/metatube/__init__.py", line 4, in <module>
    from flask_jsglue import JSGlue
  File "/usr/local/lib/python3.9/site-packages/flask_jsglue.py", line 2, in <module>                                                                                                                                 from jinja2 import Markup                                                                                                                                                                                    ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)                                                                                               Traceback (most recent call last):                                                                                                                                                                                 File "//config/metatube.py", line 5, in <module>
    from metatube import create_app, socketio
  File "/config/metatube/__init__.py", line 4, in <module>
    from flask_jsglue import JSGlue
  File "/usr/local/lib/python3.9/site-packages/flask_jsglue.py", line 2, in <module>                                                                                                                                 from jinja2 import Markup                                                                                                                                                                                    ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)                                                                                               Traceback (most recent call last):                                                                                                                                                                                 File "//config/metatube.py", line 5, in <module>
    from metatube import create_app, socketio
  File "/config/metatube/__init__.py", line 4, in <module>
    from flask_jsglue import JSGlue                                                                                                                                                                                File "/usr/local/lib/python3.9/site-packages/flask_jsglue.py", line 2, in <module>                                                                                                                                 from jinja2 import Markup                                                                                                                                                                                    ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
Traceback (most recent call last):                                                                                                                                                                                 File "//config/metatube.py", line 5, in <module>
    from metatube import create_app, socketio                                                                                                                                                                      File "/config/metatube/__init__.py", line 4, in <module>
    from flask_jsglue import JSGlue
  File "/usr/local/lib/python3.9/site-packages/flask_jsglue.py", line 2, in <module>                                                                                                                                 from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)                                                                                               Traceback (most recent call last):                                                                                                                                                                                 File "//config/metatube.py", line 5, in <module>
    from metatube import create_app, socketio
  File "/config/metatube/__init__.py", line 4, in <module>                                                                                                                                                           from flask_jsglue import JSGlue
  File "/usr/local/lib/python3.9/site-packages/flask_jsglue.py", line 2, in <module>                                                                                                                                 from jinja2 import Markup                                                                                                                                                                                    ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)                                                                                               Traceback (most recent call last):
  File "//config/metatube.py", line 5, in <module>
    from metatube import create_app, socketio
  File "/config/metatube/__init__.py", line 4, in <module>                                                                                                                                                           from flask_jsglue import JSGlue
  File "/usr/local/lib/python3.9/site-packages/flask_jsglue.py", line 2, in <module>                                                                                                                                 from jinja2 import Markup                                                                                                                                                                                    ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by Gabisonfire** [comment]
Same issue here. Woulb be nice to push tags to docker instead of overwriting latest so we can rollback in case of issue like this one :)

**Comment by alii76tt** [comment]
I don't know for sure the solution. When I searched on Stackoverflow, I came across this and tried it and it worked.
Stackoverflow: https://stackoverflow.com/a/71645733

`from jinja2 import Markup<br>
...
return Markup('<script src="%s" type="text/javascript"></script>') % (js_path,)
`

`from jinja2.utils import markupsafe 
...
return markupsafe('<script src="%s" type="text/javascript"></script>') % (js_path,)
`

**Comment by alii76tt** [comment]
I don't know for sure the solution. When I searched on Stackoverflow, I came across this and tried it and it worked.
Stackoverflow: https://stackoverflow.com/a/71645733

##### Before
> from jinja2 import Markup 
> ... 
>  return Markup('<script src="%s" type="text/javascript"></script>') % (js_path,)
#####  After
> from jinja2.utils import markupsafe
> ... 
> return markupsafe('<script src="%s" type="text/javascript"></script>') % (js_path,)

**Comment by Gabisonfire** [comment]
Yes @alii76tt that seems to be the solution, but it needs to be fixed in the library. See my post above.

**Comment by alii76tt** [comment]
Yes, definitely @Gabisonfire .

**Comment by JVT038** [comment]
Well, I guess I'll just make a fork or something, and fix it.
Or if @Gabisonfire would like to do it, I would appreciate it!

**Comment by Gabisonfire** [comment]
@JVT038 Uploaded the fix: pip install Flask-JSGlue2==0.3.2
I ended up simply forking https://github.com/italomaia/Flask-JSGlue who had already pushed the fix. Thanks @italomaia

**Comment by JVT038** [comment]
It should be fixed in https://github.com/JVT038/MetaTube/commit/43eb3b51b98e966d18e6f7ac06d182cda1544db7

**Comment by samcro1967** [comment]
@JVT038 I just removed my container and image and ran docker-compse up and am seeing the similiar issues with a new image pull. 

```
Traceback (most recent call last):
  File "//config/metatube.py", line 5, in <module>
    from metatube import create_app, socketio
  File "/config/metatube/__init__.py", line 4, in <module>
    from flask_jsglue import JSGlue
  File "/usr/local/lib/python3.9/site-packages/flask_jsglue.py", line 4, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by JVT038** [comment]
Yeah, I noticed that the fork from italomaia hadn't updated the code yet, so I'll have to do that manually.

**Comment by Gabisonfire** [comment]
I just noticed, I'm repushing it @JVT038

**Comment by Gabisonfire** [comment]
Now it throws:
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [flask_migrate] Error: Can't locate revision identified by 'c90bc7c126fd'
```

**Comment by JVT038** [comment]
Make a backup of your sqlite database before doing this (in case it doesn't work)
Anyway:
Stop the metatube container
Open your database file somehow (Either via the terminal, or via a GUI program, such as [Db Browser](https://sqlitebrowser.org/))
Then delete the table called 'alembic_version'
Now restart your container, and it should work.

**Comment by samcro1967** [comment]
It worked for me this morning after updating the image.  Knock on wood no issues thus far.
