### ISSUE TITLE
[12-01-2022 19:07] WARNING [sponsorblock.py:10]: No segments found for ...

### ISSUE THREAD

**Issue by samcro1967** [JVT038/MetaTube#4]
Seeing this error today after the update this morning.
```
[12-01-2022 19:07] INFO [sponsorblock.py:6]: Fetching sponsorblock segments for https://www.youtube.com/watch?v=123456789
[12-01-2022 19:07] WARNING [sponsorblock.py:10]: No segments found for https://www.youtube.com/watch?v=123456789
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/config/metatube/youtube.py", line 206, in fetch_video
    downloadform = downloadtemplate.render(templates=templates, segments=segments, default=defaulttemplate)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/config/metatube/templates/downloadform.html", line 58, in top-level template code
    {% set resolution = default.resolution.split(';') %}
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'resolution'
2022-01-12T19:07:43Z <Thread at 0x7f7b3e5e3040: fetch_video({'id': 'RdsGnTsHjhs', 'title': 'Artiest | TruncTitle, [<Templates 0>], 'musicbrainz', None)> failed with UndefinedError
```

**Comment by JVT038** [comment]
What did you do? I can't reproduce it, therefore I can't solve this. Which version are you using? Make sure to use the latest commit

**Comment by samcro1967** [comment]
Only change was to pull the latest docker tag.  I deleted app.db and restarted the container.  Working as expected now.  Guessing managed to get some corruption in the db somehow.

**Comment by JVT038** [comment]
Alright, glad to hear you fixed it.
And yeah, a proper versioning system is still on my todo list
