### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by theniwo** [JVT038/MetaTube#95]
My config:
```
docker run -d \                                                                                                                                               
  --name metatube \                                                                                                                                           
  --restart always \                                                                                                                                          
  -p 5000:5000 \                                                                                                                                              
  -e PORT=5000 \                                                                                                                                              
  -e HOST=0.0.0.0 \                                                                                                                                           
  -v metatube_config:/config \                                                                                                                                
  -v metatube_downloads:/downloads:rw \                                                                                                                       
  -v metatube_database:/database:rw \                                                                                                                         
  jvt038/metatube:latest
```

Error:
```
Traceback (most recent call last):
  File "//config/metatube.py", line 9, in <module>
    app = create_app()
  File "/config/metatube/__init__.py", line 46, in create_app
    init_db(app)
  File "/config/metatube/init/__init__.py", line 11, in init
    default.init_db()
  File "/config/metatube/init/create.py", line 72, in init_db
    self.migrations()
  File "/config/metatube/init/create.py", line 80, in migrations
    stamp(directory)
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 259, in stamp
    command.stamp(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 671, in stamp
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    raise ImportError("Can't find Python file %s" % path)
ImportError: Can't find Python file /config/migrations/env.py
```

upon creating file env.py

```
Traceback (most recent call last):
  File "//config/metatube.py", line 9, in <module>
    app = create_app()
  File "/config/metatube/__init__.py", line 46, in create_app
    init_db(app)
  File "/config/metatube/init/__init__.py", line 11, in init
    default.init_db()
  File "/config/metatube/init/create.py", line 72, in init_db
    self.migrations()
  File "/config/metatube/init/create.py", line 81, in migrations
    migrate(directory)
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 170, in migrate
    command.revision(config, message, autogenerate=True, sql=sql,
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 236, in revision
    scripts = [script for script in revision_context.generate_scripts()]
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 236, in <listcomp>
    scripts = [script for script in revision_context.generate_scripts()]
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 605, in generate_scripts
    yield self._to_script(generated_revision)
  File "/usr/local/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 510, in _to_script
    return self.script_directory.generate_revision(
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 667, in generate_revision
    self.revision_map.get_revisions(head),
  File "/usr/local/lib/python3.9/site-packages/alembic/script/revision.py", line 527, in get_revisions
    resolved_id, branch_label = self._resolve_revision_number(
  File "/usr/local/lib/python3.9/site-packages/alembic/script/revision.py", line 751, in _resolve_revision_number
    self._revision_map
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 1138, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.9/site-packages/alembic/script/revision.py", line 191, in _revision_map
    for revision in self._generator():
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 131, in _load_revisions
    for file_ in Script._list_py_dir(self, vers):
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 981, in _list_py_dir
    return os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/config/migrations/versions'
```
it goes on with not finding files.

Expected behaviour:

Files are getting created upon spinning up container

**Comment by JVT038** [comment]
Could you share your `docker run` command or `docker-compose.yml` file together with any environment variables?

**Comment by macross5** [comment]
Same here. I used the same docker run command as the theniwo. Seems like the docker container cant create files he needs.

**Comment by theniwo** [comment]
> Could you share your `docker run` command or `docker-compose.yml` file together with any environment variables?

sure.

```docker run -d \                                                                                                                                               
  --name metatube \                                                                                                                                           
  --restart always \                                                                                                                                          
  -p 5000:5000 \                                                                                                                                              
  -e PORT=5000 \                                                                                                                                              
  -e HOST=0.0.0.0 \                                                                                                                                           
  -v metatube_config:/config \                                                                                                                                
  -v metatube_downloads:/downloads:rw \                                                                                                                       
  -v metatube_database:/database:rw \                                                                                                                         
  jvt038/metatube:latest
  ```

My vars

```
COLOR_C=\e[0;36m
COLOR_B=\e[0;34m
SHELL=/bin/bash
LSCOLORS=ExFxCxDxBxegedabagacad
COLOR_G=\e[0;32m
f_services=/root/Settings/Linux/scripts/motd/services.sh                                           
COLOR_M=\e[0;35m
COLOR_R=\e[0;31m
COLOR_W=\e[1;37m
BC_ENV_ARGS=/root/.bc
COLOR_Y=\e[1;33m
COLOR_CLEAR=\e[0m
MCVIDEO=/nfs/MyCloud/MEDIA/VIDEO
LESS=--chop-long-lines --IGNORE-CASE --RAW-CONTROL-CHARS
d_tdir=/root/Settings/Linux/config/bash/tools
f_hosts_nextcloud=/root/Settings/Linux/config/bash/config/bash_aliases_hosts_nextcloud
COLOR_NC=\e[0m
mac_pc=08:62:66:26:08:13
MYCLOUD=/nfs/MyCloud
f_bedit=/root/Settings/Linux/config/bash/config/bedit.sh
d_docker_nas=/root/Settings/Linux/docker/nas
f_hosts_nas=/root/Settings/Linux/config/bash/config/bash_aliases_hosts_nas
mac_nas=08:60:6e:6e:d5:9e
LESS_TERMCAP_se=
LESS_TERMCAP_so=
COLOR_LGR=\e[0;37m
COLOR_WHITE=\e[1;37m
f_hosts_docker=/root/Settings/Linux/config/bash/config/bash_aliases_hosts_docker
MCNEXTCLOUD=/nfs/MyCloud/DATA/Nextcloud
mac_xp=00:01:6a:49:ff:c1
f_hosts=/root/Settings/Linux/config/bash/config/bash_aliases_hosts
COLOR_RED=\e[0;31m
f_hosts_latitude=/root/Settings/Linux/config/bash/config/bash_aliases_hosts_latitude
COLOR_LIGHT_MAGENTA=\e[1;35m
COLOR_BLUE=\e[0;34m
d_conf_bash=/root/Settings/Linux/config/bash/config
LESS_TERMCAP_ZV=
LESS_TERMCAP_ZW=
LESS_TERMCAP_ZN=
LESS_TERMCAP_ZO=
COLOR_GRAY=\e[0;30m
PWD=/root
LOGNAME=root
XDG_SESSION_TYPE=tty
COMPOSE_HTTP_TIMEOUT=240
COLOR_END=
MCDOWNLOADS=/nfs/MyCloud/DATA/Downloads
f_hosts_srv=/root/Settings/Linux/config/bash/config/bash_aliases_hosts_srv
f_hosts_pi=/root/Settings/Linux/config/bash/config/bash_aliases_hosts_pi
f_aliases=/root/Settings/Linux/config/bash/config/bash_aliases
COLOR_LIGHT_GREEN=\e[1;32m
MOTD_SHOWN=pam
d_conf=/root/Settings/Linux/config
f_nav=/root/Settings/Linux/config/bash/config/bash_aliases_nav
HOME=/root
d_docker_comp=/root/Settings/Linux/docker/hosts/keex/docker-compose
d_settings=/root/Settings
LANG=C.UTF-8
f_bashrc=/root/.bashrc
f_vars=/root/Settings/Linux/config/bash/config/bash_variables
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MCDATA=/nfs/MyCloud/DATA
COLOR_BR=\e[0;33m
PROMPT_COMMAND=history -a
COLOR_LIGHT_CYAN=\e[1;36m
COLOR_CYAN=\e[0;36m
PERL5LIB=/root/perl5/lib/perl5
f_misc=/root/Settings/Linux/config/bash/config/bash_aliases_misc
CLICOLOR=1
COLOR_YELLOW=\e[1;33m
MCMOVIES=/nfs/MyCloud/MEDIA/VIDEO/Movies
COLOR_LIGHT_RED=\e[1;31m
COLOR_LIGHT_GRAY=\e[0;37m
d_docker_pi=/root/Settings/Linux/docker/pi
SSH_CONNECTION=192.168.1.150 38184 192.168.1.8 22
d_scripts=/root/Settings/Linux/scripts
COLOR_GR=\e[0;30m
COLOR_GREEN=\e[0;32m
d_bdir=/root/Settings/Linux/config/bash/config
f_functions=/root/Settings/Linux/config/bash/config/bash_functions
MCAUDIO=/nfs/MyCloud/MEDIA/AUDIO
f_hosts_xubuntu=/root/Settings/Linux/config/bash/config/bash_aliases_hosts_xubuntu
LESSCLOSE=/usr/bin/lesspipe %s %s
f_quotes=/root/Settings/Linux/config/bash/config/quotes.sh
XDG_SESSION_CLASS=user
LESS_TERMCAP_mh=
MCMUSIC=/nfs/MyCloud/MEDIA/AUDIO/Music
TERM=xterm-color
LESS_TERMCAP_mb=
LESS_TERMCAP_me=
LESS_TERMCAP_md=
f_insulter=/root/Settings/Linux/config/bash/tools/bash-insulter/src/bash.command-not-found
PERL_MB_OPT=--install_base "/root/perl5"
LESS_TERMCAP_mr=
LESSOPEN=| /usr/bin/lesspipe %s
USER=root
MCPHOTO=/nfs/MyCloud/MEDIA/PHOTO
PERL_MM_OPT=INSTALL_BASE=/root/perl5
NC=\e[0m
LESS_TERMCAP_ue=
SHLVL=1
LESS_TERMCAP_us=
f_hosts_scorpio=/root/Settings/Linux/config/bash/config/bash_aliases_hosts_scorpio
COLOR_LIGHT_BLUE=\e[1;34m
d_docker_cont=/root/Settings/Linux/docker/hosts/keex/docker
mac_px2=68:05:ca:2a:4b:2c
mac_px1=68:05:ca:2a:12:5e
COLOR_BLACK=\e[0;30m
XDG_SESSION_ID=7911
XDG_RUNTIME_DIR=/run/user/0
MCSERIES=/nfs/MyCloud/MEDIA/VIDEO/Series
MCSCANNED=/nfs/MyCloud/DATA/Nextcloud/DATA/Documents/Scanned
SSH_CLIENT=192.168.1.150 38184 22
COLOR_MAGENTA=\e[0;35m
f_includes=/root/Settings/Linux/config/bash/config/bash_includes
MCLECTIO=/nfs/MyCloud/MEDIA/LECTIO
GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PERL_LOCAL_LIB_ROOT=/root/perl5
PATH=/root/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/.fzf/bin
d_nextcloud=/root/Nextcloud
HISTIGNORE=[ 	]*:&:[fb]g:exit
CC=\e[0m
mac_keex=00:50:08:06:37:d3
PYTHONWARNINGS=ignore::DeprecationWarning
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
COLOR_BROWN=\e[0;33m
SSH_TTY=/dev/pts/0
COLOR_LR=\e[1;31m
COLOR_LM=\e[1;35m
COLOR_LG=\e[1;32m
d_docker=/root/Settings/Linux/docker
mac_srv=6c:f0:49:e5:e7:2d
COLOR_LC=\e[1;36m
COLOR_LB=\e[1;34m
f_system=/root/Settings/Linux/config/bash/config/bash_aliases_system
MCMEDIA=/nfs/MyCloud/MEDIA
f_bconfig=/root/Settings/Linux/config/bash/config/bash_config
MCBACKUP=/nfs/MyCloud/DATA/BACKUP
_=/usr/bin/env
```

**Comment by JVT038** [comment]
Can you check if it's fixed with the latest commit by pulling the latest image? Please close if it's fixed.

**Comment by theniwo** [comment]
Now the log gives 
```
Traceback (most recent call last):
  File "//config/metatube.py", line 4, in <module>
    from metatube import create_app, socketio
  File "/config/metatube/__init__.py", line 23, in <module>
    from metatube.overview import bp as bp_overview
  File "/config/metatube/overview/__init__.py", line 4, in <module>
    from metatube.overview import routes
  File "/config/metatube/overview/routes.py", line 6, in <module>
    from metatube.metadata import MetaData
  File "/config/metatube/metadata.py", line 2, in <module>
    from importlib_metadata import metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

and the container restarts

**Comment by JVT038** [comment]
Uh, could you pull again and recreate the container?
Because if you check [metadata.py](https://github.com/JVT038/MetaTube/blob/master/metatube/metadata.py), you won't `from importlib_metadata import metadata` because I removed that line in the latest commit. So please pull and check again.

**Comment by theniwo** [comment]
Yes, sorry. 
I manage my containters with a self written script and this did not remove the old volumes.
I removed them manually and it seems to run fine now
```
Creating directory '/config/migrations/versions' ...  done
Generating /config/migrations/README ...  done
Generating /config/migrations/env.py ...  done
Generating /config/migrations/script.py.mako ...  done
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'config'
INFO  [alembic.autogenerate.compare] Detected added table 'database'
INFO  [alembic.autogenerate.compare] Detected added table 'templates'
Generating /config/migrations/alembic.ini ...  done
Please edit configuration/connection/logging settings in '/config/migrations/alembic.ini' before proceeding.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> fcdd77322a14, empty message
DEBUG [alembic.runtime.migration] new branch insert fcdd77322a14
[19-11-2023 18:05] INFO [create.py:34]: Created default rows for the configuration table
[19-11-2023 18:05] INFO [ffmpeg.py:22]: FFmpeg has been found!
[19-11-2023 18:05] INFO [create.py:60]: Created default rows for the Templates table
[19-11-2023 18:05] INFO [create.py:73]: Created the database and all necessary tables and rows

```

Closing Issue. :wave:
